package View;

import Model.Property.*;
import Model.SimulatorData;
import java.util.*;
import java.text.*;

/*******************************************************************************
 *Handles all output from the simulator
 ******************************************************************************/
public class Display
{

	/***************************************************************************
	 *Prints the bank balances of all the companies in the simulation
	 **************************************************************************/
	public static void printBankBalances(SimulatorData simData)
	{
		List<Company> companies = simData.getInterestObservers();
		DecimalFormat formatter = new DecimalFormat("#,##0.00");

		System.out.println("Bank balances: ");
		for(Company company : companies)
		{
			System.out.printf("   %s: $%s\n", company.getName(), formatter.format(company.getBankBalance()));
		}
	}

	/***************************************************************************
	 *Prints the imported year value
	 **************************************************************************/
	public static void printYear(int year)
	{
		System.out.println("\nYear: " + year);
	}

	/***************************************************************************
	 *Prints the error generated by the simulation
	 **************************************************************************/
	public static void printError(Exception e)
	{
		System.out.println("Error: " + e.getMessage());
	}
}
